"""
build_pine.py - Assemble the pasteable TradingView script.

    python build_pine.py

Concatenates jdehorty's unmodified MPL-2.0 source with our add-on block and
writes pine/lorentzian_full.pine. Keeping the two apart in the repo means the
upstream file stays byte-identical -- easy to diff against a newer release,
and unambiguous about which lines are his and which are ours.
"""
from __future__ import annotations

import os

HERE = os.path.dirname(os.path.abspath(__file__))
BASE = os.path.join(HERE, "lorentzian_classification.pine")
ADDON = os.path.join(HERE, "pine", "addon_smc_brackets.pine")
OUT = os.path.join(HERE, "pine", "lorentzian_full.pine")

BANNER = """
// ############################################################################
// #  Everything ABOVE this line is jdehorty's "Machine Learning: Lorentzian  #
// #  Classification", MPL-2.0, unmodified. Everything BELOW is the add-on    #
// #  layer, re-derived from public ICT/SMC definitions.                      #
// #                                                                          #
// #  Generated by build_pine.py -- edit the two source files, not this one.  #
// ############################################################################
"""


def main() -> None:
    for path in (BASE, ADDON):
        if not os.path.exists(path):
            raise SystemExit(f"missing input: {path}")

    base = open(BASE, encoding="utf-8").read().rstrip()
    addon = open(ADDON, encoding="utf-8").read().lstrip()

    # Pine's default max_boxes_count is 50 and the add-on draws three boxes per
    # signal (TP2/TP1/SL zones) plus one per tracked order block. Without this
    # the oldest boxes silently vanish after ~16 signals. Patched here rather
    # than edited into the upstream file so that file stays byte-identical.
    old_decl = "overlay=true, precision=4, max_labels_count=500)"
    new_decl = ("overlay=true, precision=4, max_labels_count=500, "
                "max_boxes_count=500, max_lines_count=500)")
    if old_decl not in base:
        raise SystemExit(
            "could not find the indicator() declaration to patch -- upstream "
            "changed shape; re-check build_pine.py against the new source")
    base = base.replace(old_decl, new_decl, 1)

    # TradingView caps shorttitle at 10 characters and rejects the script on
    # save otherwise. Upstream's is 30 ("Lorentzian Classification v2.0"), which
    # the compiler now flags as SHORT_TITLE_TOO_LONG.
    old_short = 'shorttitle="Lorentzian Classification v2.0"'
    new_short = 'shorttitle="LC v2"'
    if old_short not in base:
        raise SystemExit(
            "could not find the shorttitle to patch -- upstream changed shape")
    base = base.replace(old_short, new_short, 1)

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(base + "\n\n" + BANNER + "\n" + addon)

    n = sum(1 for _ in open(OUT, encoding="utf-8"))
    print(f"wrote {OUT} ({n} lines)")
    print("Paste it into TradingView -> Pine Editor -> Save -> Add to chart.")


if __name__ == "__main__":
    main()
